### ISSUE TITLE
Awesome plugins: Post your plugins/themes here

### ISSUE THREAD

**Issue by nomi-san** [PenguLoader/PenguLoader#4] opened 2022-10-18 20:29 UTC
I found some **themes** on GitHub.
You can inbox me to put it here.

Any theme has screenshots, please use `img` tag with 300px height.

```html
<img src="//screenshot-url.png" height="300" />
```

### Noxus in #2
[🔽  Download Noxus.zip](https://github.com/nomi-san/league-loader/files/8916280/Noxus.zip)

<img src="https://i.imgur.com/qEm5VZc.png" height="300" />

// credit: Janna# Discord

### Cute by @PrincessAkira
https://github.com/PrincessAkira/league-launcher-theme

<img src="https://user-images.githubusercontent.com/38210249/212605344-c7c907b1-22d0-48cb-ab3a-b86223141b7b.png" height="300" />

### Irelia-Theme by @rumi-chan
https://github.com/rumi-chan/Irelia-Theme

<img src="https://user-images.githubusercontent.com/38210249/212605233-e2ab8400-8cc0-452f-b99d-00f76b093096.png" height="300" />

**Comment by nomi-san** [comment] 2022-10-18 20:51
### Original Mecha plugins
https://github.com/vperpl/sex-ploits/releases/tag/J%23e

### Noxus like themes
https://github.com/Zanthirr/Zanthirr.github.io
https://github.com/chineseswag/chineseswag.github.io
https://github.com/Turbo-123/turbo-123.github.io
https://github.com/Trankzz/Rengar-theme

**Comment by thinhthui** [comment] 2023-01-14 15:28
**Removed Rating Label (VN Server)**
add this css to your js file. : https://ahrixthinh.xyz/LoL%20client%20ui/ui.css

**Comment by Roydevil** [comment] 2023-01-15 14:32
> **Removed Rating Label (VN Server)** add this css to your js file. : https://ahrixthinh.xyz/LoL%20client%20ui/ui.css **Lain Theme (Font Updated)** https://ahrixthinh.xyz/LoL%20client%20ui/Lain.css ![image](https://user-images.githubusercontent.com/111081318/212522497-1ab20539-4384-41cb-af6b-0b886511aafd.png) if i make anymore theme, i'll post it here : http://ahrixthinh.xyz/lolloader.html

it doesn't work on my css bruh 💀
![image](https://user-images.githubusercontent.com/94338907/212546788-69bc2a33-71a8-48db-9945-dc9f8e6f41e3.png)

**Comment by Roydevil** [comment] 2023-01-15 14:39
Elaina Themes

https://github.com/Roydevil/Elaina-theme/releases/tag/v1.0.1

* L2d Background version
![image](https://user-images.githubusercontent.com/94338907/212547083-e053c741-046f-4e92-a4d8-f4a2e4cc8b8e.png)

* Static Background version
![image](https://user-images.githubusercontent.com/94338907/212547221-83b34070-ae4e-44df-9403-4b0e78ededc7.png)

**Comment by thinhthui** [comment] 2023-01-15 17:58
> > **Removed Rating Label (VN Server)** add this css to your js file. : https://ahrixthinh.xyz/LoL%20client%20ui/ui.css **Lain Theme (Font Updated)** https://ahrixthinh.xyz/LoL%20client%20ui/Lain.css ![image](https://user-images.githubusercontent.com/111081318/212522497-1ab20539-4384-41cb-af6b-0b886511aafd.png) if i make anymore theme, i'll post it here : http://ahrixthinh.xyz/lolloader.html
> 
> it doesn't work on my css bruh 💀

which one didn't work ?

**Comment by Roydevil** [comment] 2023-01-16 05:55
> > > **Removed Rating Label (VN Server)** add this css to your js file. : https://ahrixthinh.xyz/LoL%20client%20ui/ui.css **Lain Theme (Font Updated)** https://ahrixthinh.xyz/LoL%20client%20ui/Lain.css if i make anymore theme, i'll post it here : http://ahrixthinh.xyz/lolloader.html
> > 
> > 
> > it doesn't work on my css bruh 💀
> 
> which one didn't work ?

oops, it put it to bottom of my theme and it work fine 😅

**Comment by Roydevil** [comment] 2023-01-16 08:29
Skadi Themes

https://github.com/Roydevil/Skadi-Theme/releases

( idk how to use video as a background so someone help me pls )

![image](https://user-images.githubusercontent.com/94338907/212631801-00c1394f-1975-4fa9-84c1-c17dafde5bd7.png)

![image](https://user-images.githubusercontent.com/94338907/212631844-21cf0624-11f9-4d87-93c1-714f40eb1146.png)

**Comment by nomi-san** [comment] 2023-01-16 08:42
@Roydevil 
> ( idk how to use video as a background so someone help me pls )

Large dimension GIFs' size can bigger than original video.
If the background uses `<img>` tag, you can put a video inside it.

For using images only, you can do a plugin with slideshow and transition effects.

**Comment by Roydevil** [comment] 2023-01-16 08:44
> 

tks i will try it

**Comment by thinhthui** [comment] 2023-01-16 08:57
> Skadi Themes
> 
> https://github.com/Roydevil/Skadi-Theme/releases
> 
> ( idk how to use video as a background so someone help me pls )
> 
> <img alt="" height="300" src="https://user-images.githubusercontent.com/94338907/212631801-00c1394f-1975-4fa9-84c1-c17dafde5bd7.png">
> 
> <img alt="" height="300" src="https://user-images.githubusercontent.com/94338907/212631844-21cf0624-11f9-4d87-93c1-714f40eb1146.png">

make a div that play video as a background since background does not support video

**Comment by Roydevil** [comment] 2023-01-16 09:00
> 



> > Skadi Themes
> > https://github.com/Roydevil/Skadi-Theme/releases
> > ( idk how to use video as a background so someone help me pls )
> > <img alt="" height="300" src="https://user-images.githubusercontent.com/94338907/212631801-00c1394f-1975-4fa9-84c1-c17dafde5bd7.png">
> > <img alt="" height="300" src="https://user-images.githubusercontent.com/94338907/212631844-21cf0624-11f9-4d87-93c1-714f40eb1146.png">
> 
> make a div that play video as a background since background does not support video

💀

**Comment by Roydevil** [comment] 2023-01-16 15:33
> 
> make a div that play video as a background since background does not support video

well, i don't know much about css, can you help me this pls 😳

**Comment by thinhthui** [comment] 2023-01-16 19:36
> > make a div that play video as a background since background does not support video
> 
> well, i don't know much about css, can you help me this pls 😳

on my site (above) at home tab there is a link to discord, go there and i can help you.

**Comment by Roydevil** [comment] 2023-01-17 14:03
**Elaina Themes** 

https://github.com/Roydevil/Elaina-theme

- Static version

![image](https://user-images.githubusercontent.com/94338907/212918792-95bcc336-8bf1-43db-83f0-28d2bb896b3e.png)

- L2d version

![image](https://user-images.githubusercontent.com/94338907/212918448-3826749d-00b0-4d57-a0d4-fffc43b6313d.png)


**Skadi Theme**

https://github.com/Roydevil/Skadi-Theme

![image](https://user-images.githubusercontent.com/94338907/212918173-420a5f61-3698-4d36-a25c-c0a5df21f715.png)

**Comment by Roydevil** [comment] 2023-01-19 14:00
**Theme Template for League Loader**

https://github.com/Roydevil/Theme-Template

**Comment by teisseire117** [comment] 2023-01-22 10:57
![fOD1Peq](https://user-images.githubusercontent.com/43145883/213912178-840fc625-9396-47fc-bd79-9744391aeada.png)
Made a button to auto-accept queue. I'm a newbie in programmation so there probably was a better way to do this.

```
window.auto_accept = false

function autoAcceptQueueButton(){
	let element = document.getElementById("autoAcceptQueueButton")
	if (element.attributes.selected != undefined) {
		window.auto_accept = false
		element.removeAttribute("selected")
	}
	else {
		element.setAttribute("selected", "true")
		window.auto_accept = true
	}
}

window.autoAcceptQueueButton = autoAcceptQueueButton

async function subscribe() {
	const uri = document.querySelector('link[rel="riot:plugins:websocket"]').href
	const ws = new WebSocket(uri, 'wamp')

	ws.onopen = () => ws.send(JSON.stringify([5, 'OnJsonApiEvent']))
	ws.onmessage = async message => {
		if (window.phase == "ReadyCheck" && window.auto_accept) {
			await acceptMatchmaking()
			window.phase = "ReadyCheckAccepted"
		}
	}
}

window.addEventListener('DOMContentLoaded', () => {
	subscribe()
	var observer = new MutationObserver(function(mutations) {
		if (document.querySelector(".v2-footer-notifications.ember-view") != null && document.getElementById("autoAcceptQueueButton") == null) {
			let newOption = document.createElement("lol-uikit-radio-input-option");
			newOption.setAttribute("id", "autoAcceptQueueButton");
			newOption.setAttribute("onclick", "window.autoAcceptQueueButton()");
			if (window.auto_accept){
				newOption.setAttribute("selected", "");
			}
			newOption.innerHTML = "Auto Accept";

			let parentElement = document.querySelector(".v2-footer-notifications.ember-view");
			parentElement.append(newOption);
		}
	});
	observer.observe(document, {childList: true, subtree:true});
})

async function acceptMatchmaking() {
	await fetch("/lol-matchmaking/v1/ready-check/accept", {
		"headers": {
			"accept": "application/json",
			"accept-language": "en-US,en;q=0.9",
			"content-type": "application/json",
			"sec-ch-ua": "\"Chromium\";v=\"91\"",
		},
		"body": null,
		"method": "POST",
	});
}
```

**Comment by nomi-san** [comment] 2023-01-22 13:09
@teisseire117 

>```js
>window.auto_accept = false
>window.phase;
>```

Each script is a separate module, you should use local variables instead.
```js
let auto_accept = false

if (cond) auto_accept = true
if (auto_accept) doSomething()
```

To listen for a specific API call, you can try this, e.g `/lol-gameflow/v1/gameflow-phase`:
```js
const API = '/lol-gameflow/v1/gameflow-phase'

ws.onopen = () => {
  ws.send(JSON.stringify([5, 'OnJsonApiEvent' + API.replace(/\//g, '_')]))
  // => OnJsonApiEvent_lol-gameflow_v1_gameflow-phase
  // send more to subscribe multiple events
}
ws.onmessage = async message => { /*...*/ }
```

Accept matchmaking API has no body and no need to add these headers, except `content-type` if body is JSON string.
```js
const acceptMatchmaking = () => fetch('/lol-matchmaking/v1/ready-check/accept', { method: 'POST' })
```

**Comment by teisseire117** [comment] 2023-01-22 16:24
> @teisseire117
> 
> > ```js
> > window.auto_accept = false
> > window.phase;
> > ```
> 
> Each script is a separate module, you should use local variables instead.
> 
> ```js
> let auto_accept = false
> 
> if (cond) auto_accept = true
> if (auto_accept) doSomething()
> ```
> 
> To listen for a specific API call, you can try this, e.g `/lol-gameflow/v1/gameflow-phase`:
> 
> ```js
> const API = '/lol-gameflow/v1/gameflow-phase'
> 
> ws.onopen = () => {
>   ws.send(JSON.stringify([5, 'OnJsonApiEvent' + API.replace(/\//g, '_')]))
>   // => OnJsonApiEvent_lol-gameflow_v1_gameflow-phase
>   // send more to subscribe multiple events
> }
> ws.onmessage = async message => { /*...*/ }
> ```
> 
> Accept matchmaking API has no body and no need to add these headers, except `content-type` if body is JSON string.
> 
> ```js
> const acceptMatchmaking = () => fetch('/lol-matchmaking/v1/ready-check/accept', { method: 'POST' })
> ```

I made the fixes. I first used local variable but I had an issue and I thought it was caused by that so I went with Global variables, but the issue was probably due to something else

**Comment by teisseire117** [comment] 2023-01-23 06:55
As I plan on making a few other plug-ins, I thought it would be better to have the base be better built. And I also made a repository because copy/pasting them is gonna be complicated : 
https://github.com/teisseire117/league-loader-plugins/tree/main/plugins

**Comment by Sheelia** [comment] 2023-01-24 22:17
> As I plan on making a few other plug-ins, I thought it would be better to have the base be better built. And I also made a repository because copy/pasting them is gonna be complicated : https://github.com/teisseire117/league-loader-plugins/tree/main/plugins
> 
> edit: Made a new plug-in : https://github.com/teisseire117/league-loader-plugins/blob/main/plugins/auto_message_upon_arriving_champ_select.js It will automatically send a message in champ-select chat, and post-lobby chat(every new player joining delay the message by 1 second, the goal is to make sure everyone see it) I use it to advertise my website but you could use it to call role or anything else
> 
> The two plug-ins I want to make is one to display back the hidden usernames in lobby(programs exist that do it but they're ugly and don't modify the client directly so they're bothersome to use)
> 
> And the other one I want it to be connected to chatgpt but to do what exactly is to be determined


Waiting Impatiently

**Comment by teisseire117** [comment] 2023-01-25 02:56
new plug-in requested by someone : https://github.com/teisseire117/league-loader-plugins/blob/main/plugins/dodge_button.js

It adds a Dodge button in the lobby. It allows to dodge without closing the client 
![xGwVnrU](https://user-images.githubusercontent.com/43145883/214470371-a1d570a4-6439-4ce8-84e3-3994081b5527.png)

**Comment by teisseire117** [comment] 2023-01-28 01:11
added a new plug-in "offline mode"(but it really is mostly a status changer button)

It allows you to click on your status to change it.

Note:

- If you are in a lobby, you can fake your status to display you are in-game, as shown here : 
![swEwviF](https://user-images.githubusercontent.com/43145883/215233265-7c7df683-b17c-44e6-a6fd-11bea09481d3.png)

- If you set your status to offline/away, when you create a lobby or join a queue it will momentarily show that you are doing that. But will soon switch back to Offline. This is a bit annoying, however 99% of the time you'll been shown as away/offline properly.

Here is a video showing this interaction : https://streamable.com/nke4c3

**Comment by Roydevil** [comment] 2023-01-28 06:41
> new plug-in requested by someone : https://github.com/teisseire117/league-loader-plugins/blob/main/plugins/dodge_button.js
> 
> It adds a Dodge button in the lobby. It allows to dodge without closing the client ![xGwVnrU]()

Bruh this plugin even doesn't need ur _utils.js file delete some code and it still work 🐧

**Comment by Roydevil** [comment] 2023-01-28 15:27
@nomi-san can you create a button that open plugins folder 
It's inconvenient to find that every time 🐧

**Comment by nomi-san** [comment] 2023-01-28 16:53
> can you create a button that open plugins folder

No problem for JS functions, like `openDevTools()`.
```js
window.openPluginsFolder();
```

You can open new issues for feature request.

**Comment by teisseire117** [comment] 2023-01-30 14:29
Made a Rem theme : 

https://user-images.githubusercontent.com/43145883/215504702-6583079c-53ad-4893-abb4-1ba09681c8c8.mp4



From this repository you'll need rem_style.js, and rem_style.css (to be put in assets folder) : https://github.com/teisseire117/league-loader-plugins/tree/main/plugins

**Comment by oMaikeru** [comment] 2023-02-09 15:21
I dont have any kind of knowledge about js and css so could anyone make a clean minimalist black and white theme with default hud for me?

**Comment by oMaikeru** [comment] 2023-02-09 18:35
Hello i tried to make a full clean minimalist black and white theme but after 3 hours of trying nothing worked could anyone do it for me?

**Comment by oMaikeru** [comment] 2023-02-09 20:46
im trying to make my own theme (just a minimalist back theme since im a newbie) is there anyway to change also the loading screen background to black (the "loading please wait..." screen when u swap between loot and store)? if yes whats the class? also let me know if u have any other suggestions

```
@import url('https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=Orbitron&display=swap');

:root {
    background: url(https://raw.githubusercontent.com/oMaikeru/Michael-Theme/main/Static/BG.jpg) !important;
}
.parties-view .parties-background {
    opacity:0;
}
.collections-application{
    background: url(https://raw.githubusercontent.com/oMaikeru/Michael-Theme/main/Static/BG.jpg) !important;
}
.rcp-fe-viewport-sidebar{
    background: linear-gradient(rgb(0 0 0), rgb(0 0 0)) !important;
}
.navbar-blur{
    background: linear-gradient(180deg,rgb(0 0 0) 46.02%, rgb(0 0 0)100%) !important;
}
.lol-social-identity.ember-view{
    background-color: black !important;
}
.lobby-header-overlay{
    background: linear-gradient(180deg,rgb(0 0 0) 29.17%, rgb(0 0 0 / 0%) 100%) !important;
}
.loot-contents{
    background-color: black !important;
}
.loot-backdrop.background-static {
    background-image: url(https://raw.githubusercontent.com/oMaikeru/Michael-Theme/main/Static/BG.jpg);
}
.store-backdrop {
    background-image: url(https://raw.githubusercontent.com/oMaikeru/Michael-Theme/main/Static/BG.jpg);
}
```

**Comment by 909oce** [comment] 2023-02-10 12:06
> 

id recommend checking out the discord server for questions like that, im sure someone can help you out :)

**Closed** 2024-01-02 04:41 UTC
Labels: enhancement, help wanted
